### ISSUE TITLE
USER STORY: Footer with Essential Info, Links, Newsletter and Legal Data

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#12]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic # | Construct Footer |
| User Story # | As a user, I want to see a footer at the page's end so that I get access to additional vital information, social media links, useful links, newsletter and legal data, etc. |
| Story Points | 2 |

## Description
**As a** user

**I want** to see a footer at the page's end

**So that** I get access to additional vital information, social media links, useful links, newsletter and legal data, etc.

## Acceptance Criteria
1. Reuser, adapt, and modify the footer used in a previous project to fast development
2. Develop a newsletter section for later adaptation
3. Implement a proper design and social media buttons

## Tasks
- [x] Use a proper footer template for our project, adapting the shapes, layout, and colors
- [x] Create the newsletter option/input for future adaptation
- [x] Make sure it has social media buttons as seen from the skeleton & that the design is consistent

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
