### ISSUE TITLE
USER STORY: 'Sign In/Up' with Dashboard Access

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#13]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic # | Link to Header |
| User Story # | As a user or admin, I want a header link to 'sign in and sign up' so that I can validate my login details on a separate page and access my dashboard. |
| Story Points | 7 |

## Description
**As a** user or admin

**I want** I want a header link to 'sign in or sign up'

**So that**  I can validate my login details on a separate page and access my dashboard

## Acceptance Criteria
1. Create a temporary header design for 'sign in and sign up' for testing purposes (optional)
2. Develop a custom template for sign-in and sign-up
3. Implement a user & admin dashboard
4. Make sure it redirects to the user and admin dashboard after login and signup functionality

## Tasks
- [x] Develop a custom header just to include visually our login and signup functionality
- [x] Implement a custom template that will override Django's default template for these purposes
- [x] Install the user dashboard template and split it into one for users and one for admins
- [x] Make sure after login and signup to redirect to the correct dashboard based on the user role
- [x] Verify the sign in/signup functionalities work perfectly

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
Change user story point to 4 due to complexity

**Comment by plexoio** [comment]
User story completed, it took more than expected due to the initial set up and personal reasons.
