### ISSUE TITLE
USER STORY: Social Media Login/Signup for Secure, Smooth Access

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#14]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic # | Social Media Login |
| User Story # | As a user or admin, I want the option to log in or sign up using a social media account so that I have a secure and smooth interaction with the system. |
| Story Points | 7 |

## Description
**As a** User/Admin

**I want** I want the option to log in or sign up using a social media account

**So that** I have a secure and smooth interaction with the system.

## Acceptance Criteria
1. Implement social media logic with Google
2. Make sure the button is available on the sign-in and sign-up page
3. After login redirect to the respective user/admin dashboard
4. Remember this is just an attempt, it is not guaranteed.

## Tasks
- [x] Check on Google and the LMS how to implement social media login
- [x] Develop a login button with Google Style
- [x] Implement Logic so that when the user is logged in it redirects to the user/admin dashboard

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
Added custom login button as seen from the code directly or our dedicated documentation: https://plexoio.github.io/py/developer-snack/google_auth/#step-4-login-button
