### ISSUE TITLE
USER STORY: Role-Specific Dashboard with Key Stats for Efficient Use

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#15]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic # | Create User & Admin Dashboard |
| User Story # | As a user or admin, after logging in or signing up, I want a useful dashboard with key stats & menu options relevant to my role so that  I can enable secure and efficient system interaction. |
| Story Points | 7 |

## Description
**As a** user or admin,  after logging in or signing up

**I want** I want a useful dashboard with key stats & menu options relevant to my role

**So that**  I can enable secure and efficient system interaction.

## Acceptance Criteria
1. Implement a bootstrap admin template for the dashboard design
2. Make sure the menu options are set for future features
3. Design the main dashboard page to show only user's related information

## Tasks
- [x] Install a proper bootstrap admin template and adapt it to our project's need
- [x] Make sure the menu and side nav bar is responsive & their style aligns to the design of our project
- [x] Edit & develop the main dashboard page to display only key information and links as an overview for fast and convenient access

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
Complete important parts, adapt and enhance in future itereations
