### ISSUE TITLE
USER STORY: Dashboard Profile Management for Data Control and Privacy

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#16]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic # | Build User & Admin Profile Management |
| User Story # | As a user or admin, I want a section on the dashboard where I can edit and manage my profile so that I have control over my data and safeguard my privacy. |
| Story Points | 7 |

## Description
**As a** User/Admin

**I want** I want a section on the dashboard where I can edit and manage my profile

**So that** I have control over my data and safeguard my privacy.

## Acceptance Criteria
1. Create a settings section for user details management
2. The settings must display current user information, password, and email update functionality
3. The styling must align with the overall style
4. At all times check the structure plane for more details and the user profile database model

## Tasks
- [x] Add to the dropdown section the settings entry
- [x] Make sure to READ all current user data and allow to update (conditionally) password, email, first name, last name, user type, etc.
- [x] Stablish a harmonic design for the form and button
- [x] Verify the admin/user settings features are functional

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
All completed. Styling is needed in further iterations.
