### ISSUE TITLE
USER STORY: Dashboard Account Deletion for Privacy Preservation

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#18]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Sign in/up & Dashboard |
| Epic # | Delete Account Option |
| User Story # | As a user, I want the option to delete my account from the dashboard so that I can preserve my privacy. |
| Story Points | 4 |

## Description
**As a** user

**I want**  I want the option to delete my account from the dashboard

**So that** I can preserve my privacy.

## Acceptance Criteria
1. Implement a proper view & template for this functionality accessible from the user settings
2. Edit the template & explain/warn users of their action
3. Make sure there is a message at the end of the process that lets the user know their account has been deleted

## Tasks
- [ ] Develop referencing previous projects how to implement this functionality and adapt where needed
- [ ] Edit the template to let users know the consequences of the account deletion based on the user's model, and make changes to the DB if needed.
- [ ] Implement a message feature on the login page, where users will land after account deletion

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
