### ISSUE TITLE
USER STORY: Admin Dashboard for Creating and Showcasing Digital Products & Services

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#19]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Product & Service Management |
| Epic # | Establish Admin 'Product & Service' Creation |
| User Story # | As an admin, I want to create, update & delete digital products & services from my dashboard and showcase them on the homepage so that I can leverage the software marketplace's potential. |
| Story Points | 13 |

## Description
**As an** Admin
 
**I want**  I want to create digital products & services from my dashboard and showcase them on the homepage

**So that** I can leverage the software marketplace's potential.

## Acceptance Criteria
1. Implement independent product & service creation from the admin dashboard
2. Develop the necessary form and views to achieve this
3. Add independent pages to read the current product & service entries created allowing you to update & delete them
4. Design a proper layout on the backend and a simple one on the frontend for future development

## Tasks
- [x] Create a section for service & product creation using a simple view first
- [x] Create the necessary views that will be linked to the product creation view (Category, etc.)
- [x] Edit the current views to achieve the desired functionality, watch out for the model scope, change if needed
- [x] Implement a read, edit & delete section for created products & services
- [x] Make sure the design is unique & aligned with our final style

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
All was completed successfully with a delay due to personal issues. Expecting extension approbal from the agentur fur arbeit.
