### ISSUE TITLE
USER STORY: User-Friendly Header for Easy Navigation and Feature Access

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#2]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic # | Design Header |
| User Story # | As a user, I want a clean, user-friendly header at the top of the page, so I can navigate easily and access the system's key features through the menu and dropdowns. |
| Story Points | 4 |

## Description
**As a** User

**I want** a clean, user-friendly header at the top of the page

**So that**  I can navigate easily and access the system's key features through the menu and dropdowns.

## Acceptance Criteria
1. Make sure the header is spacious enough to fit the search engine icon
2. Follow the skeleton prototype & surface plane at all times to keep coherence
3. Implement responsiveness or make sure the template being used has it by default

## Tasks
- [x] Find a proper icon for the search engine and implement the code to trigger the search input
- [x] Follow the skeleton prototype & surface plane for keywords, interactions, colors, positions & styling in general
- [x] Select and install the best template that aligns with the marketplace, and reuse snippets of code from the last project if needed

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
Update the story point to 4 due to the fact that we need to look for and install a template for the marketplace

**Comment by plexoio** [comment]
Change the approach we start from the user backend
