### ISSUE TITLE
USER STORY: Detailed 'Buy Now' Page for Informed Purchasing

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#20]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Product & Service Management |
| Epic # | Design Product & Service Page |
| User Story # | As a user, I want a separate page detailing the product or service I click on 'Buy Now' so that I can initiate the purchase process and access more detailed information not present on the homepage. |
| Story Points | 7 |

## Description
**As a** user

**I want** a separate page detailing the product or service I click on 'Buy Now'

**So that**  I can initiate the purchase process and access more detailed information not present on the homepage.

## Acceptance Criteria
1. Develop dedicated page for product that will be rendered when users click on 'Buy now or Hire now' from the homepage.
2. Make sure the new page displays more information compared to the homepage.
3. Follow up the skeleton and surface plane for other elements to be displayed on this single page.

## Tasks
- [x]  Create necessary view and template for this functionality, wiring up all necessary things.
- [x]  Check the model and skeleton to know what key data we should display
- [x]  Keep design and interaction consistency

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
