### ISSUE TITLE
USER STORY: Success Alerts for Action Confirmation and Awareness

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#21]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Product & Service Management |
| Epic # | Enable System Feedback |
| User Story # | As a user or admin, I want to receive success alerts or messages after certain system actions, like account creation or product purchase so that I keep enhancing my awareness of the actions taken. |
| Story Points | 7 |

## Description
**As a** user or admin

**I want** to receive success alerts or messages after certain system actions, like account creation or product purchase

**So that** I keep enhancing my awareness of the actions taken.

## Acceptance Criteria
1. Use Django technologies for consistency
2. Adapt the feedback messages to the current template style
3. Pay attention to user and admin interactions and add the feedback functionality

## Tasks
- [x] Make use of the Django messages library at all times to display proper feedback to the users on the front end, also useful for debugging purposes.
- [x] Create style properties and apply to them based on the message tags for success, error, info, etc.
- [x] Implement messages to the user and admin interaction when needed.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
We keep this user story through out our development. It becomes almost natural when developing, an indispensable tool.
