### ISSUE TITLE
USER STORY: Visibility on Product Metrics for Insight and Popularity

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#22]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Product & Service Management |
| Epic # | Develop Product & Service Metrics |
| User Story # | As a user or admin, I want visibility on product or service metrics, such as purchase counts, likes, and comments, both on the homepage and dedicated pages so that they provide insight into the product's popularity and additional data. |
| Story Points | 13 |

## Description
**As a** user or admin

**I want**  visibility on product or service metrics, such as purchase counts, likes, and comments, both on the homepage and dedicated pages

**So that** they provide insight into the product's popularity and additional data.

## Acceptance Criteria
1. Adapt implementation keeping design consistency
2. Leverage the current models, the power of Django, and previous code implementation to achieve these metrics
3. Add counts for likes, purchases, and comments counts

## Tasks
- [x] Follow the skeleton to know where to display the metrics
- [x] Use or create models and code logic where necessary be it on the frontend template or backend
- [x] Add counts for likes, purchases, and comments counts and implement all necessary logic, views & models for this.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
All has been implemented. Consider adding comment counts on the homepage in future iterations.
