### ISSUE TITLE
USER STORY: Role-Based Privilege Visualization for Full Website Use

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#23]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Product & Service Management |
| Epic # | Configure Role Visualization |
| User Story # | As a user, visitor, or admin, I want a visual representation of my privileges based on my role so that it helps me realize the website's full potential. |
| Story Points | 7 |

## Description
**As a** As a user, visitor, or admin

**I want** I want a visual representation of my privileges based on my role

**So that** so that it helps me realize the website's full potential.

## Acceptance Criteria
1. Implement this feature on the frontend & backend so better user experience
2. Design the message using the Django built-in messages feature and adapt it to the current design
3. Incite users to click on the link in the message to read more about the current scope

## Tasks
- [x] Edit templates for the frontend  and for the backend & add code there (settings page)
- [x] Make sure the message is displaying an alert-info with bootstrap style (just for welcoming to the dashboard)
- [x] Create a dedicated page for registered users to see their current role scope
- [x] Make sure the anchor link is also present on the role field on the settings page.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
