### ISSUE TITLE
USER STORY: Smooth Cart-to-Purchase-to-Download  Journey

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#24]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Product & Service Management |
| Epic # | Integrate Cart, Purchase & Download |
| User Story # | As a user, I want to add products to my cart, experience a smooth payment process, and download the digital product immediately after payment so that I can minimize friction in my purchasing journey. |
| Story Points | 13 |

## Description
**As a** user

**I want** to add products to my cart, experience a smooth payment process, and download the digital product immediately after payment

**So that** I can minimize friction in my purchasing journey.

## Acceptance Criteria
1. Implement the frontend logic for the shopping cart first and then add the item option.
2. Develop the other necessary features following the LMS.
3. Make sure the user's frontend and backend are displaying and relating properly.
4. Create necessary views or adapt them where needed.

## Tasks
- [x] Develop following the LMS the shopping cart.
- [x] Implement other extra buffer features.
- [x] Create the payment method gateways, focus first on Stripe.
- [x] Modify the views and models if needed.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
This current iteration has lasted longer than expected. We have learned empirically that implementations as such require different user stories and not only one. However, we proceed with this one due to time constraints.

**Comment by plexoio** [comment]
""" Download file protection with: user is_authenticated,
    user has placed an order, secret UUID token for file name,
    str token for url name & renaming of the file when downloading with
    Download model file_name.
    All designed to hide the UUID token as the actual file name.
    Remember to include permission on server production."""

**Comment by plexoio** [comment]
Not used any more but useful for the future to trigger a file download:

``` html
<script>
    // Decode the URL-encoded password parameter
    var encodedPassword = "{{ request.GET.password }}";
    var password = decodeURIComponent(encodedPassword);
    if (password) {
        // Create a hidden link element and trigger the download
        var downloadLink = document.createElement('a');
        downloadLink.href = 'data:text/plain;charset=utf-8,' + encodeURIComponent(password);
        downloadLink.download = 'password.txt';
        downloadLink.style.display = 'none';
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);
    }
</script>
```

**Comment by plexoio** [comment]
Remember this too for encoding the password if needed:

```python
from urllib.parse import quote
encoded_password = quote(password)
return redirect(reverse('checkout_success', args=[order.order_number, encoded_password]))
```

**Comment by plexoio** [comment]
For the Download model to limit downloads with passed time:

```python
    def is_valid(self):
        expiration_time = timezone.now() - timezone.timedelta(seconds=5)
        return self.created_on >= expiration_time
```

**Comment by plexoio** [comment]
Implementation completed after some hard work. New things were added to our developer snack for future use. All implementation is working, stripe payment, download, webhook and user feedback, etc.
