### ISSUE TITLE
USER STORY: Category' Menu for Streamlined Product & Service Search

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#26]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Search & Filter |
| Epic # | Develop Category Menu |
| User Story # | As a user, I want a 'Category' menu so that it streamlines my search for products & services. |
| Story Points | 4 |

## Description
**As a** User

**I want** a 'Category' menu

**So that** it streamlines my search for products & services. 

## Acceptance Criteria
1. Implement category choices on the menu for both products and services.
2. Leverage the current code and template for fast development
3. Make sure the category names are unique in the database

## Tasks
- [x] Add proper fields on the base.html menu section based on categories to filter
- [x] Reuse or adapt the current view and template if needed to achieve this particular goal
- [x] Write unique alt_name for categories in the database for unique access from the Menu

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
We have leveraged the AllProductServiceListView for this implementation
