### ISSUE TITLE
USER STORY: Search Engine for Specific Product or Service Discovery

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#27]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Search & Filter |
| Epic # | Incorporate Search Bar |
| User Story # | As a user, I want a search engine so I that I can find specific products or services. |
| Story Points | 7 |

## Description
**As a** _<role>_,

**I want** _<capability>_,

**So that** _<received benefit>_.

## Acceptance Criteria
1. Connect backend logic for the frontend search engine
2. Develop views if necessary
3. Make sure the development is scalable

## Tasks
- [x] Follow the LMS for proper development
- [x] Develop necessaty views and templates for proper display or products & services
- [x] Make sure the search engine development is scalable for other specific purposes such as categories...

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
Important to remember the logic for thee search engine: class AllProductServiceListView(generic.ListView):
    """Dedicated page for displaying list of all products & services and
    instances from the search engine implementation."""
    model = Product
    template_name = 'all_product_service/all_product_service.html'
    paginate_by = 6

    # Search Engine logic starts here
    search = None
    searched_items = None

    def get(self, request, *args, **kwargs):
        self.search = request.GET.get('q')
        if self.search:
            if not self.search:
                messages.error(
                    request, 'Search ERROR: Enter a keyword to start searching!')
                return redirect('combined_items_all')

            # Get the combined list
            combined_list = self.combine_products_and_services(
                list(Product.objects.filter(status=2).order_by('-created_on')),
                list(Service.objects.filter(status=2).order_by('-created_on'))
            )

            # Filter the combined list
            self.searched_items = [
                item for item in combined_list if self.search.lower(
                ) in item.title.lower(
                ) or self.search.lower() in item.description.lower()]

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        # If searched_items run this
        if self.searched_items is not None:
            return self.searched_items

        # If NOT searched_items run this
        try:
            products = list(Product.objects.filter(
                status=2).order_by('-created_on'))
            services = list(Service.objects.filter(
                status=2).order_by('-created_on'))

            combined_list = self.combine_products_and_services(
                products, services)
            return combined_list
        except Exception as e:
            print(e)
            return []

    def get_context_data(self, **kwargs):
        # From here on the code will run based on get_queryset results
        context = super().get_context_data(**kwargs)

        combined_list = self.get_queryset()

        paginator = Paginator(combined_list, self.paginate_by)
        page_number = self.request.GET.get('page', 1)

        try:
            page_obj = paginator.page(page_number)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
        except PageNotAnInteger:
            page_obj = paginator.page(1)

        context['page_obj'] = page_obj
        context['is_paginated'] = len(combined_list) > self.paginate_by
        context['search_keyword'] = self.search
        return context

    def combine_products_and_services(self, products, services):
        # This can run for the get() & get_queryset()
        combined_list = []
        while products or services:
            if products:
                combined_list.append(products.pop(0))
            if services:
                combined_list.append(services.pop(0))
            if products:
                combined_list.append(products.pop(0))
        return combined_list

**Comment by plexoio** [comment]
Consider this suggestion:

If you want to continue using the `Q` object, you will need to modify your `get_queryset` method such that it doesn't convert the QuerySets into lists prematurely. Instead, you should combine them and then filter using the `Q` objects. 

Here's an example of how to adjust:

1. Modify `get_queryset`:
```python
def get_queryset(self):
    try:
        products = Product.objects.filter(status=2).order_by('-created_on')
        services = Service.objects.filter(status=2).order_by('-created_on')
        
        combined_query = products.union(services)  # Assuming they have the same columns
        return combined_query
    except Exception as e:
        print(e)
        return Product.objects.none()  # Empty QuerySet
```

2. Modify your `get` method:
```python
from django.db.models import Q

def get(self, request, *args, **kwargs):
    if request.GET.get('q'):
        search = request.GET['q']
        if not search:
            messages.error(request, 'Search ERROR: Enter a keyword to start searching!')
            return redirect('combined_items_all')
        
        searches = Q(title__icontains=search) | Q(description__icontains=search)
        self.queryset = self.get_queryset().filter(searches)

    return super().get(request, *args, **kwargs)
```

This approach involves the following:

- `get_queryset` will return a combined QuerySet of `products` and `services`, not a list.
- The `get` method filters the combined QuerySet using the `Q` object and then assigns it to `self.queryset`.

Please note that using `.union()` requires that both `products` and `services` have the same columns (fields). If they don't have the exact same fields, `.union()` will throw an error. In that case, you might have to consider other strategies to combine the QuerySets or rethink the database design to allow for such operations.

**Comment by plexoio** [comment]
New adaptation:

```python
class AllProductServiceListView(generic.ListView):
    """Dedicated page for displaying list of all products & services and
    instances from the search engine implementation."""
    model = Product
    template_name = 'all_product_service/all_product_service.html'
    paginate_by = 6

    # Search Engine logic starts here
    search = None
    searched_items = None

    def get(self, request, *args, **kwargs):
        # .strip() to remove any accidental whitespace
        self.search = request.GET.get('q', '').strip()

        # Check if search keyword is empty or only consists of whitespace
        if not self.search:
            messages.error(
                request, 'The search bar cannot be empty!')
            return super().get(request, *args, **kwargs)

        # If search keyword exists, proceed with the search logic
        combined_list = self.combine_products_and_services(
            list(Product.objects.filter(status=2).order_by('-created_on')),
            list(Service.objects.filter(status=2).order_by('-created_on'))
        )

        # Filter the combined list based on the search keyword
        self.searched_items = [
            item for item in combined_list if self.search.lower(
            ) in item.title.lower() or self.search.lower(
            ) in item.description.lower()
        ]

        # Check if searched_items was filled with results
        if not self.searched_items:
            messages.info(request, 'No results found for your search.')

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        # If searched_items run this
        if self.searched_items is not None:
            return self.searched_items

        # If NOT searched_items run this
        try:
            products = list(Product.objects.filter(
                status=2).order_by('-created_on'))
            services = list(Service.objects.filter(
                status=2).order_by('-created_on'))

            combined_list = self.combine_products_and_services(
                products, services)
            return combined_list
        except Exception as e:
            logger.error(f"Error fetching products and services: {e}")
            return []

    def get_context_data(self, **kwargs):
        # From here on the code will run based on get_queryset results
        context = super().get_context_data(**kwargs)

        combined_list = self.get_queryset()

        paginator = Paginator(combined_list, self.paginate_by)
        page_number = self.request.GET.get('page', 1)

        try:
            page_obj = paginator.page(page_number)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
        except PageNotAnInteger:
            page_obj = paginator.page(1)

        context['page_obj'] = page_obj
        context['is_paginated'] = len(combined_list) > self.paginate_by
        return context

    def combine_products_and_services(self, products, services):
        # No rearranging of the list is necessary with this approach

        combined_list = []

        # Convert lists to iterators
        product_iter = iter(products)
        service_iter = iter(services)

        # Flags to check if iterators have more items
        has_more_products = True
        has_more_services = True

        # Combine products and services
        while has_more_products or has_more_services:
            if has_more_products:
                try:
                    combined_list.append(next(product_iter))
                except StopIteration:
                    has_more_products = False

            if has_more_services:
                try:
                    combined_list.append(next(service_iter))
                except StopIteration:
                    has_more_services = False

        return combined_list
```
