### ISSUE TITLE
USER STORY: On-Page Filters for Sorting by Categories, Price, and More

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#28]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Search & Filter  |
| Epic # | Integrate Filter Function |
| User Story # | As a user, I want a filter section on the same page so that I can sort by categories, price, license, ownership, etc. |
| Story Points | 7 |

## Description
**As a** User

**I want** a filter section on the same page

**So that** I can sort by categories, price, license, ownership, etc.

## Acceptance Criteria
1. Create a new view for sorting Product and service model instances
2. Implement a template reusing the previous one for searching
3. Make sure it is scalable to implement the on-page sorting

## Tasks
- [x] Create a view that will render products & services independently
- [x] Reuse template from the all product & template view
- [x] Keep modularity to handle better the development of this feature

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
Consider this code if necessary in the future:

```html
<div class="row">
            <div class="col-lg-4 col-md-12 mb-5 col-sm-12 order-md-last">
                <div class="sort-select-wrapper w-50">
                    <select id="sort-selector"
                        class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                        <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...
                        </option>
                        <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low
                            to
                            high)</option>
                        <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price
                            (high
                            to low)</option>
                        <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating
                            (low
                            to high)</option>
                        <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating
                            (high to low)</option>
                        <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)
                        </option>
                        <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)
                        </option>
                        <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>
                            Category
                            (A-Z)</option>
                        <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>
                            Category (Z-A)</option>
                    </select>
                </div>
            </div>
        </div>
```

```html
<li><a class="dropdown-item" href="{% url 'sorted' %}?sort=price&direction=asc">By Price</a></li>
```

**Comment by plexoio** [comment]
Before changes:

```python
class SortedProductServiceListView(generic.ListView):
    '''
    View for sorting products & services
    '''
    model = Product
    template_name = 'sorted_product_service/sorted_product_service.html'
    paginate_by = 6
    context_object_name = 'combined_items'

    def get_queryset(self):
        sortkey = self.request.GET.get('sort', 'created_on')
        direction = self.request.GET.get('direction', 'asc')

        try:
            if sortkey == 'title':
                products = Product.objects.annotate(
                    lower_title=Lower('title')).order_by('lower_title')
                services = Service.objects.annotate(
                    lower_title=Lower('title')).order_by('lower_title')
            else:
                products = Product.objects.all().annotate(
                    likescount=Count('likes'),
                    transactionscount=Count('transactions')).order_by(sortkey)
                services = Service.objects.all().annotate(
                    likescount=Count('likes'),
                    transactionscount=Count('transactions')).order_by(sortkey)
        except Exception as e:
            logger.error(f"Error while sorting products and services: {e}")
            messages.error(self.request, 'That was not a valid sorting value.')
            return []

        products = products.filter(status=2)
        services = services.filter(status=2)

        combined_list = self.combine_products_and_services(
            list(products),
            list(services)
        )

        if direction == 'desc':
            combined_list.reverse()

        self.sortkey = sortkey
        self.direction = direction

        return combined_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        combined_list = context['combined_items']

        unique_categories = list(
            set([item.category for item in combined_list]))

        context['sortkey'] = self.sortkey
        context['direction'] = self.direction
        context['categories'] = unique_categories
        return context

    def combine_products_and_services(self, products, services):
        combined_list = []
        product_iter = iter(products)
        service_iter = iter(services)

        has_more_products = True
        has_more_services = True

        while has_more_products or has_more_services:
            if has_more_products:
                try:
                    combined_list.append(next(product_iter))
                except StopIteration:
                    has_more_products = False

            if has_more_services:
                try:
                    combined_list.append(next(service_iter))
                except StopIteration:
                    has_more_services = False

        return combined_list
```

After Changes:

```python
class SortedProductServiceListView(generic.ListView):
    '''
    View for sorting products & services
    '''
    model = Product
    template_name = 'sorted_product_service/sorted_product_service.html'
    paginate_by = 6
    context_object_name = 'combined_items'

    def get_queryset(self):
        sortkey = self.request.GET.get('sort', 'created_on')
        direction = self.request.GET.get('direction', 'asc')
        self.sortkey = sortkey
        self.direction = direction

        products = Product.objects.filter(status=2).annotate(
            lower_title=Lower('title'),
            likescount=Count('likes'),
            transactionscount=Count('transactions')).order_by('created_on')

        services = Service.objects.filter(status=2).annotate(
            lower_title=Lower('title'),
            likescount=Count('likes'),
            transactionscount=Count('transactions')).order_by('created_on')

        combined_list = self.combine_products_and_services(
            list(products),
            list(services)
        )

        try:
            if sortkey == 'title':
                combined_list.sort(key=lambda item: item.title.lower())
            elif sortkey == 'likescount':
                combined_list.sort(key=lambda item: float(item.likescount))
            elif sortkey == 'transactionscount':
                combined_list.sort(
                    key=lambda item: float(item.transactionscount))
            elif sortkey == 'price':
                combined_list.sort(key=lambda item: float(item.price))
            elif sortkey == 'category':
                combined_list.sort(
                    key=lambda item: item.category.category_name.lower())
            else:
                combined_list.sort(key=lambda item: item.created_on)

        except Exception as e:
            logger.error(f"Error while sorting products and services: {e}")
            messages.error(self.request, 'That was not a valid sorting value.')
            return []

        if direction == 'desc':
            combined_list.reverse()

        return combined_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        combined_list = context['combined_items']

        unique_categories = list(
            set([item.category for item in combined_list]))

        context['sortkey'] = self.sortkey
        context['direction'] = self.direction
        context['categories'] = unique_categories
        return context

    def combine_products_and_services(self, products, services):
        combined_list = []
        product_iter = iter(products)
        service_iter = iter(services)

        has_more_products = True
        has_more_services = True

        while has_more_products or has_more_services:
            if has_more_products:
                try:
                    combined_list.append(next(product_iter))
                except StopIteration:
                    has_more_products = False

            if has_more_services:
                try:
                    combined_list.append(next(service_iter))
                except StopIteration:
                    has_more_services = False

        return combined_list

```
