### ISSUE TITLE
USER STORY: Post-Purchase Like and Comment Features for Community Engagement

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#29]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Likes & Comments |
| Epic # | Implement Likes & Comments |
| User Story # | As a user, after a purchase, I want to like and comment on my product or service, and share my thoughts so that I can contribute to the community. |
| Story Points | 7 |

## Description
**As a** user, after a purchase, 

**I want** to like and comment on my product or service and share my thoughts

**So that** I can contribute to the community.

## Acceptance Criteria
1. Implement like & comment functionality keeping design consistency
2. Make sure the models are sufficient, if not, update them or create new ones
3. Develop backend and frontend logic, using always user-centric design

## Tasks
- [x] Follow the skeleton for proper development
- [x] Leverage the models created or create new ones
- [x] Make sure the user and admin can read or update the likes & comments respectively
- [x] Keep in mind the user-centric design, progressive disclosure and simplicity

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.

**Comment by plexoio** [comment]
Comment functionality complete

**Comment by plexoio** [comment]
Like functionality complete
