### ISSUE TITLE
USER STORY: Cards with Key 'Product' Info for Informed Clicking

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#7]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic # | Present Product Cards in Rows |
| User Story # | As a user, I want each card to display key 'Product' information, so that I know what I'm clicking on. |
| Story Points | 4 |

## Description
**As a** user

**I want**  each card to display key 'Product' information

**So that**  I know what I'm clicking on.

## Acceptance Criteria
1. Implement the comprehensive data display for this row.
2. Reuse the code from the previous row to keep consistency, and make necessary changes for this specific row.
3. Adapt the view if necessary & follow along our skeleton & surface.

## Tasks
- [ ] Create a comprehensive data display using templating language to access the model.
- [ ] Keep design consistency at all times.
- [ ] Make sure the data displayed goes along with our plan. Notice how the category tag is different for this row: category and not 'instance' type.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
