### ISSUE TITLE
USER STORY: Exclusive 'Service' Section for Easy Preview

### ISSUE THREAD

**Issue by plexoio** [plexoio/py#9]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Homepage |
| Epic # | Display Service Cards in Rows |
| User Story # | As a user, I want a 'Service' section below the 'Product' row, focusing exclusively on services so that I can preview them. |
| Story Points | 4 |

## Description
**As a** user

**I want** a 'service' section below the 'Product' row that showcases only services

**So that** I can preview them.

## Acceptance Criteria
1. Implement a row under the product combined cards.
2. Design the cards just as the above row to keep consistency.
3. Create necessary views and templates to achieve this.

## Tasks
- [x] Create a view for only services that will be rendered on the homepage as well.
- [x] Design the cards based on the principles already acquired from Bootstrap for consistency and responsiveness.
- [x] Create views in a way that can be rendered on the same homepage and pay attention to details to avoid bugs.
- [x] Reuse previous code to accelerate development. Do not repeat yourself.

## Notes
* Articulate this criterion collaboratively with the User, Product Owner, and Agile Team.
* Remember: Adding an item to the backlog doesn't guarantee delivery. It represents an option for the team.
* The Product Backlog is dynamic and may change based on feedback and changes.
* The purpose of Backlog Refinement is to ensure sufficient development-ready items.
* Prioritizing items in the Product Backlog is the responsibility of the Product Owner.
* The Development Team is responsible for estimating user stories and allocating work for development.

The "Tasks" section will help the team break down the user story into manageable pieces of work, aiding in planning and tracking progress.
